[package]
name = "ws_ping"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ["WebSocket","MessageEvent"] }
futures = "0.3"
js-sys = "0.3"